services:

    seeddms:
        image: usteinm/seeddms:latest    
        container_name: seeddms
        restart: unless-stopped            
        ports:
            - "8200:80"
            - "8443:443"
        environment:
            - TZ=Europe/Madrid            
        volume:
            - ./seeddms-data:/var/lib/seeddms/data
            - ./seeddms-conf:/var/lib/seeddms/conf
            - ./dms-data:/var/www/seeddms/data
